
DATE=`date +%Y%m%d`
ARCH=vgg16
GPU=2

SYNTH=1 ARCH=${ARCH} LOG=LOG${DATE}-AUTOWS-ORG INSIZE=224 BATCHSIZE=32 GPU=${GPU} ./go.sh
SYNTH=1 ARCH=${ARCH} LOG=LOG${DATE}-AUTOWS-AUTO INSIZE=224 BATCHSIZE=32 GPU=${GPU} AUTO=1 ./go.sh
SYNTH=1 ARCH=${ARCH} LOG=LOG${DATE}-AUTOWS-AUTOWS INSIZE=224 BATCHSIZE=32 AUTOWS=1 GPU=${GPU} ./go.sh
