
DATE=`date +%Y%m%d`

ARCH="vgg16"

SYNTH=1 ARCH=${ARCH} LOG=LOG${DATE}-224-LWR-ORG INSIZE=224 BATCHSIZE=32 LWR="0" ./go-parallel.sh
SYNTH=1 ARCH=${ARCH} LOG=LOG${DATE}-224-LWR-LWR INSIZE=224 BATCHSIZE=32 LWR="1" ./go-parallel.sh
